### ISSUE TITLE
Rename: `apacheCamelModelVersion` -> `version`

### ISSUE THREAD

**Issue by tadayosi** [hawtio/camel-model#2]
The variable name `apacheCamelModelVersion` is a bit lengthy and we can rename it to a shorter name `version`, because it should be still clear that it's the version of the Camel model.

@phantomjinx Is there any reason we should keep this long name?

**Comment by phantomjinx** [comment]
Nope. Just down to my need to be overly descriptive. ;-)

**Comment by tadayosi** [comment]
To fix it, I noticed that we need to modify the schema generator plugin. Also, now I've reconsidered it and the descriptive name `apacheCamelModelVersion` isn't so bad, as it's descriptive ;-) and the shorter name `version` might cause name collisions in imported namespaces since `version` is a commonly used variable name. Users can name an alias like:
```js
import { apacheCamelModelVersion as version } from '@hawtio/camel-model'
```
if they want a shorter name.

Let's close this as "won't fix".
